### ISSUE TITLE
In version 1.11, does it still support nodejs v14 or v16?

### ISSUE THREAD

**Issue by Gao-pw** [isaacs/path-walker#20]
hello, When I upgraded to version 1.11, it no longer worked in my project. 🥲

**Comment by isaacs** [comment]
What error are you encountering? "No longer works" isn't enough information.

**Comment by martoncsukas** [comment]
Please see https://github.com/isaacs/rimraf/issues/306, probably related.

**Comment by isaacs** [comment]
@martoncsukas That issue does not provide any more details, unfortunately. "Doesn't work on my machine" isn't any more helpful than "works on my machine", and the bin being loaded in that issue is not the one shipped with the latest rimraf.

**Comment by Gao-pw** [comment]
> What error are you encountering? "No longer works" isn't enough information.

sorry🥺,this is the wrong message from my ci environment
```
fatal - Error: Register plugin /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/dist/index.js failed, since Cannot find module 'node:path'
 Require stack:
- /tfsagent/agent-dev1/_work/87/s/node_modules/path-scurry/dist/commonjs/index.js
- /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/node_modules/glob/dist/cjs/glob.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/node_modules/glob/dist/cjs/index.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/node_modules/glob/dist/cjs/index-cjs.js
- /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/node_modules/rimraf/dist/cjs/src/index.js
- /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/node_modules/rimraf/dist/cjs/src/index-cjs.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max-plugin-openapi/dist/index.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/core/dist/service/plugin.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/core/dist/service/pluginAPI.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/core/dist/index.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/umi/dist/service/service.js
- /tfsagent/agent-dev1/_work/87/s/node_modules/umi/dist/cli/cli.js
- /tfsagent/agent-dev1/_work/87/s/node_modules/umi/dist/index.js
- /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max/dist/cli.js
 - /tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/max/bin/max.js
     at Plugin.apply (/tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/core/dist/service/plugin.js:76:15)
    at Service.initPlugin (/tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/core/dist/service/service.js:463:33)
     at Service.run (/tfsagent/agent-dev1/_work/87/s/node_modules/@umijs/core/dist/service/service.js:259:18)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
     at async Service.run2 (/tfsagent/agent-dev1/_work/87/s/node_modules/umi/dist/service/service.js:65:12)
    at async run (/tfsagent/agent-dev1/_work/87/s/node_modules/umi/dist/cli/cli.js:56:7)
```
In my CI environment, node version is 14.

**Comment by isaacs** [comment]
> `Cannot find module 'node:path'`

> In my CI environment, node version is 14.

Are you quite sure of that? Because it looks like it's not node at all.  `node:path` module can't even be overridden, it's guaranteed to be node's path module in the later releases of node v14.

Please add a `console.log(process.version)` in your program somewhere before this crash occurs, to guarantee that it's actually for real definitely 100% node v14 in the specific process environment where this error occurs.

Because I don't buy it. Sounds like you're being lied to somewhere along the chain, or you're getting an especially old node 14 release. And since node 14 is EOL anyway, for over a year now, I'm kinda inclined to say you're on your own.

**Comment by Gao-pw** [comment]
> > `Cannot find module 'node:path'`
> 
> > In my CI environment, node version is 14.
> 
> Are you quite sure of that? Because it looks like it's not node at all. `node:path` module can't even be overridden, it's guaranteed to be node's path module in the later releases of node v14.
> 
> Please add a `console.log(process.version)` in your program somewhere before this crash occurs, to guarantee that it's actually for real definitely 100% node v14 in the specific process environment where this error occurs.
> 
> Because I don't buy it. Sounds like you're being lied to somewhere along the chain, or you're getting an especially old node 14 release. And since node 14 is EOL anyway, for over a year now, I'm kinda inclined to say you're on your own.

Sorry for the late reply. I confirmed that the node version is 14.17.5

**Comment by isaacs** [comment]
Does it work on 14.18? That's the min in the package.json engines field. `14 >=14.18`

**Comment by isaacs** [comment]
It may be that upgrading jest fixes this. Some others have reported that it didn't support node: prefixed modules, but I believe it's fixed in the latest version.
